{% set name = "stanscofi" %}
{% set version = "9999" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "../dist/{{ name }}-{{ version }}.tar.gz"

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - pip
    - python

  run:
    - cute-ranking >=0.0.3
    - scikit-learn >=1.3.0
    - matplotlib
    - tqdm >=4.65.0
    - codecarbon >=2.2.5
    - umap-learn
    - seaborn >=0.12.2

test:
  imports:
    - stanscofi

about:
  home: https://github.com/RECeSS-EU-Project/stanscofi
  license: MIT
  license-file: LICENSE
  summary: "Package for STANdard drug Screening by COllaborative FIltering. Performs benchmarks against datasets and SotA algorithms, and implements training, validation and testing procedures."

extra:
  recipe-maintainers:
    - RECeSS-EU-Project
