name: conda 

on: [push, pull_request]

jobs:
  conda-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - run: sed -i "s:9999:1.0.1:" setup.py recipes/conda/meta.yaml
      env:
          VERSION: ${{ github.ref }}
    - uses: s-weigand/setup-conda@v1
    - name: prepare
      run: |
        python setup.py sdist bdist_wheel
        conda install -y anaconda-client conda-build conda-verify
        conda config --set channel_priority strict
        conda config --set anaconda_upload yes
    - name: build
      run: |
        cd recipes/conda/
        conda config --set anaconda_upload no
        conda build --override-channels -c conda-forge .
        ls
#        conda build --user recess --token $ANACONDA_TOKEN --override-channels -c conda-forge .
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    - uses: actions/upload-artifact@v3
      with:
      name: my-artifact
      path: path/to/artifact/world.txt
