name: Release documentation
on: [push,pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python -m pip install -r pip/requirements.txt
          python -m pip install .
          python3 -m pip install sphinx sphinx-gallery Pillow sphinx-rtd-theme
      - name: Sphinx build
        run: |
          sphinx-apidoc -f -o docs/ src/stanscofi --implicit-namespace
          sphinx-build docs _build
      - name: Deploy documentations
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true