name: Release documentation
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python3 -m pip install -r pip/requirements.txt && python -m pip install .
      - name: Sphinx build
        run: |
          sphinx-apidoc -f -o docs/stanscofi src/stanscofi
          sphinx-build docs _build
      - name: Deploy documentations
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true