name: stanscofi post-pushing testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} using Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          use-mamba: true
          mamba-version: "*"
      - name: Install dependencies and build stanscofi
        run: |
          conda activate test
          python -m pip install --upgrade pip
          pip install -r recipes/pip/requirements.txt
          pip install --use-pep517 -e . 
          python -c "import stanscofi; import stanscofi.datasets; import stanscofi.utils; import stanscofi.validation; import stanscofi.models; import stanscofi.training_testing; import stanscofi.preprocessing; print('stanscofi has been successfully installed and importable in Python.')"
      - name: Test datasets module
        run: |
          cd tests/ && python -m tests_datasets
      - name: Test training_testing module
        run: |
          cd tests/ && python -m tests_training_testing
      - name: Test preprocessing module
        run: |
          cd tests/ && python -m tests_preprocessing
      - name: Test models module
        run: |
          cd tests/ && python -m tests_models
      - name: Test validation module
        run: |
          cd tests/ && python -m tests_validation