name: stanscofi post-pushing testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} using Miniconda
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and build stanscofi
        run: |
          pip install --upgrade pip
          python -m pip install -r recipes/pip/requirements.txt
          python -m pip install .
      - name: Test import
        run: |
          python -c "import stanscofi; import stanscofi.datasets; import stanscofi.utils; import stanscofi.validation; import stanscofi.models; import stanscofi.training_testing; import stanscofi.preprocessing; print('stanscofi has been successfully installed and is importable in Python.')"
      - name: Test datasets module
        working-directory: ./tests/
        run: |
          python -m test_datasets
      - name: Test preprocessing module
        working-directory: ./tests/
        run: |
          python -m test_preprocessing
      - name: Test validation module
        working-directory: ./tests/
        run: |
          python -m test_validation
      - name: Test models module
        working-directory: ./tests/
        run: |
          python -m test_models
      - name: Test training_testing module
        working-directory: ./tests/
        run: |
          python -m test_training_testing