name: stanscofi post-pushing testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} using Miniconda
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and build stanscofi
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r pip/requirements.txt
          python -m pip install .
      - name: Test import stanscofi
        run: |
          python -c "import stanscofi; import stanscofi.datasets; import stanscofi.utils; import stanscofi.validation; import stanscofi.models; import stanscofi.training_testing; import stanscofi.preprocessing; print('stanscofi has been successfully installed and is importable in Python.')"
      - name: Test datasets module
        working-directory: ./tests/
        run: |
          python -m test_datasets
      - name: Test preprocessing module
        working-directory: ./tests/
        run: |
          python -m test_preprocessing
      - name: Test validation module
        working-directory: ./tests/
        run: |
          python -m test_validation
      - name: Test models module
        working-directory: ./tests/
        run: |
          python -m test_models
      - name: Test training_testing module
        working-directory: ./tests/
        run: |
          python -m test_training_testing
#      - name: Test codecov
#        working-directory: ./
#        run: |
#          pip install codecov
#          pip install pytest-cov
#          pytest --cov=./ --cov-report=xml
#          codecov
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}