name: stanscofi post-pushing testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} using Miniconda
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and build stanscofi
        run: |
          python -m pip install -r recipes/pip/requirements.txt
          python -m pip install .
      - name: Test import
        run: |
          python -c "import stanscofi; import stanscofi.datasets; import stanscofi.utils; import stanscofi.validation; import stanscofi.models; import stanscofi.training_testing; import stanscofi.preprocessing; print('stanscofi has been successfully installed and importable in Python.')"
      - name: Test datasets module
        working-directory: ./tests/
        run: |
          python tests_datasets.py
      - name: Test training_testing module
        working-directory: ./tests/
        run: |
          python tests_training_testing.py
      - name: Test preprocessing module
        working-directory: ./tests/
        run: |
          python tests_preprocessing.py
      - name: Test models module
        working-directory: ./tests/
        run: |
          python tests_models.py
      - name: Test validation module
        working-directory: ./tests/
        run: |
          python tests_validation.py